### ISSUE TITLE
实现多线程修改zookeeper中货币信息

### ISSUE THREAD

**Issue by laazy** [se-kiwi/ds-lab#9]
使用至少四个线程来同步修改zookeeper中存储的货币信息。

**Comment by yfzm** [comment]
Solved by commit [f6338bc](https://github.com/se-kiwi/ds-lab/commit/f6338bc5a26ad49df860ce36265e82ec47f90e5a), [b0bf4db](https://github.com/se-kiwi/ds-lab/commit/b0bf4db89bcd6b6d39f7711396551ae5d4401b40) and [1c55f4c](https://github.com/se-kiwi/ds-lab/commit/1c55f4c53bb8a8afb39c7453e7021e3f84b27d6b)
